---
deployment:
  tasks:
    - export DEPLOYPATH=/home/magerngu/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp contributing.md $DEPLOYPATH
    - /bin/cp license.txt $DEPLOYPATH
    - /bin/cp readme.rst $DEPLOYPATHS